### ISSUE TITLE
Decide on what should happen with the Feather bibliography

### ISSUE THREAD

**Issue by martindholmes** [UVicHCMC/BBTI#7]
The original site had a page for this:

https://wayback.archive-it.org/org-467/20190903110019/http://bbti.bodleian.ox.ac.uk/feather/

but it has this disclaimer:

`````
The copyright in the original published list remains with the [Oxford Bibliographical Society](https://wayback.archive-it.org/org-467/20190903110019/http://www.oxbibsoc.org.uk/).
Many thanks to Prof Feather and the Society for permission to add the list to the BBTI website.
The additional material was provided by Paul Morgan - to whom many thanks also.
`````

The new site builds this page, but before we link to it, I believe we should obtain separate permission from the copyright holders.

**Comment by martindholmes** [comment]
Per MB, we are OK to publish this; she'll check with JF himself.

**Comment by martindholmes** [comment]
The original site allowed subselection of Feather biblio items based on place; we have a TEI `<pubPlace>` component in the metadata so we should probably have a separate column containing that value so that people can sort based on that. Publication date was not a separate datapoint in the original source data, unfortunately, so we can't easily break that out.

**Comment by JanelleJenstad** [comment]
The publication list is not very long. I'm happy to tag the dates with `<date when="YYYY">` and then do a pull request so we can model how to enrich the dataset.

**Comment by JanelleJenstad** [comment]
@martindholmes: Are you still making corrections in the TSV files or can I start tagging dates in the XML files?

**Comment by martindholmes** [comment]
I'm still correcting the TSV files; there's a lot still to be done there, and I think the community needs to make the decision about how and when we leave them behind.

**Comment by martindholmes** [comment]
There's a lot of mystery around the dates in general; I'm going to raise a detailed ticket on that to try to get some feedback from the people who created the dataset. Those suffixes are quite problematic.

**Comment by martindholmes** [comment]
@JanelleJenstad See this issue on dates (warning -- it's long):

https://github.com/UVicHCMC/BBTI/issues/10

**Comment by martindholmes** [comment]
This is in the release now.
